
let data = [
    {
        "name":"Table",
        "cost":1000,
        "incart":false,
        "category":"Furniture",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":1,
        "counter":1
    },
    {
        "name":"Chair",
        "cost":900,
        "incart":false,
        "category":"Furniture",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":2,
        "counter":1
    },
    {
        "name":"Sofa",
        "cost":9000,
        "incart":false,
        "category":"Furniture",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":3,
        "counter":1
    },
    {
        "name":"EarPhones",
        "cost":1000,
        "incart":false,
        "category":"Electronics",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":4,
        "counter":1
    },
    {
        "name":"Headphones",
        "cost":2000,
        "incart":false,
        "category":"Electronics",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":5,
        "counter":1
    },
    {
        "name":"Tv",
        "cost":10000,
        "incart":false,
        "category":"Electronics",
        "img":"https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/amazon-rivet-furniture-1533048038.jpg",
        "id":6,
        "counter":1
    }
]

export default data;